// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AddSource } from "./AddSource";
import type { ChecksumSpec } from "./ChecksumSpec";
import type { ConflictPolicy } from "./ConflictPolicy";
import type { Credentials } from "./Credentials";
import type { HeaderPair } from "./HeaderPair";
import type { MediaRequest } from "./MediaRequest";
import type { StartMode } from "./StartMode";

/**
 * Request to add a new download.
 */
export type AddDownloadRequest = { url: string, 
/**
 * Desired file name; detected from the server when omitted.
 */
file_name: string | null, 
/**
 * Target directory; derived from settings and category when omitted.
 */
save_dir: string | null, referer: string | null, user_agent: string | null, headers: Array<HeaderPair>, 
/**
 * Value of the `Cookie` header supplied by the browser (sensitive).
 */
cookies: string | null, credentials: Credentials | null, 
/**
 * Maximum parallel connections for this download (1..=32).
 */
connections: number | null, queue_id: string | null, start: StartMode, 
/**
 * Milliseconds since epoch at which the download should start.
 */
scheduled_at: number | null, checksum: ChecksumSpec | null, media: MediaRequest | null, source: AddSource, 
/**
 * Size reported by the browser, if any.
 */
expected_size: number | null, mime: string | null, priority: number | null, 
/**
 * Per-download speed limit in bytes/second (0 or None = unlimited).
 */
speed_limit: number | null, conflict: ConflictPolicy | null, 
/**
 * Page on which the link was found (for display and referer fallback).
 */
page_url: string | null, };
