// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where an add request came from.
 */
export type AddSource = "user" | "browser" | "context_menu" | "video_button" | "clipboard" | "batch";
