// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThemeMode } from "./ThemeMode";

export type AppearanceSettings = { theme: ThemeMode, 
/**
 * "system", "en" or "ar".
 */
language: string, 
/**
 * Columns visible in the download table.
 */
visible_columns: Array<string>, };
