// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppInfo = { name: string, version: string, os: string, arch: string, data_dir: string, log_dir: string, 
/**
 * Secrets are persisted (OS credential store available).
 */
secure_storage: boolean, 
/**
 * The updater has a signing key configured.
 */
updater_configured: boolean, protocol_version: number, };
