// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppearanceSettings } from "./AppearanceSettings";
import type { BrowserSettings } from "./BrowserSettings";
import type { DownloadSettings } from "./DownloadSettings";
import type { GeneralSettings } from "./GeneralSettings";
import type { MediaSettings } from "./MediaSettings";
import type { NetworkSettings } from "./NetworkSettings";
import type { PowerSettings } from "./PowerSettings";
import type { UpdateSettings } from "./UpdateSettings";

/**
 * The complete settings document.
 */
export type AppSettings = { general: GeneralSettings, downloads: DownloadSettings, network: NetworkSettings, browser: BrowserSettings, media: MediaSettings, power: PowerSettings, appearance: AppearanceSettings, updates: UpdateSettings, 
/**
 * The first-run onboarding was completed.
 */
onboarding_done: boolean, };
