// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BatchFailure } from "./BatchFailure";
import type { DownloadInfo } from "./DownloadInfo";

export type BatchAddResult = { added: Array<DownloadInfo>, failed: Array<BatchFailure>, };
