// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BrowserInfo } from "./BrowserInfo";
import type { ExtensionSeen } from "./ExtensionSeen";

export type BrowserIntegrationStatus = { browsers: Array<BrowserInfo>, 
/**
 * Path of the native messaging host binary, if found.
 */
host_path: string | null, 
/**
 * Extensions currently connected.
 */
connected: number, last_extension: ExtensionSeen | null, 
/**
 * Folders with the unpacked extensions shipped with the app.
 */
chromium_extension_dir: string | null, firefox_extension_dir: string | null, chromium_extension_id: string, firefox_extension_id: string, };
