// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BrowserSettings = { 
/**
 * Take over browser downloads matching `capture_extensions`.
 */
capture_downloads: boolean, 
/**
 * File extensions captured from the browser.
 */
capture_extensions: Array<string>, 
/**
 * Do not capture files smaller than this (bytes, 0 = no limit).
 */
min_capture_size: number, 
/**
 * Sites (host patterns) never captured.
 */
excluded_sites: Array<string>, 
/**
 * Detect video/audio resources on web pages.
 */
video_detection: boolean, 
/**
 * Show the floating "Download This Video" button.
 */
floating_button: boolean, 
/**
 * Extra extension IDs allowed to talk to the native host (store builds).
 */
extra_allowed_extension_ids: Array<string>, };
