// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One browser's integration state.
 */
export type BrowserInfo = { id: string, name: string, 
/**
 * "chromium" or "firefox".
 */
family: string, installed: boolean, 
/**
 * The native messaging host is registered for this browser.
 */
registered: boolean, manifest_path: string | null, error: string | null, 
/**
 * Extension store page, once the extension is published there.
 */
store_url: string | null, };
