// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * File category used for sidebar filters and optional category folders.
 */
export type Category = "video" | "music" | "document" | "archive" | "program" | "image" | "other";
