// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A URL seen on the clipboard (only when the user enabled monitoring).
 */
export type ClipboardUrl = { url: string, };
