// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What to do when the target file already exists.
 */
export type ConflictPolicy = "rename" | "overwrite";
