// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Username / password for HTTP Basic, FTP or SFTP authentication.
 * Never persisted in plaintext; see `velox-persistence::secrets`.
 */
export type Credentials = { username: string, password: string, };
