// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DailyStat = { 
/**
 * Local date "YYYY-MM-DD".
 */
day: string, bytes: number, files: number, };
