// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DownloadSettings = { 
/**
 * Maximum downloads running simultaneously across all queues.
 */
max_concurrent: number, 
/**
 * Default maximum connections per download (1..=32).
 */
connections_per_download: number, 
/**
 * Adapt the connection count to measured throughput and server limits.
 */
adaptive_connections: boolean, 
/**
 * Do not split segments smaller than this (bytes).
 */
min_segment_size: number, 
/**
 * Automatic retries before a download is marked failed.
 */
max_retries: number, 
/**
 * Base delay between retries, seconds (grows exponentially).
 */
retry_delay_secs: number, 
/**
 * Global speed limit, bytes/second (0 = unlimited).
 */
speed_limit: number, 
/**
 * Directory for partial files (empty = next to the final file).
 */
temp_dir: string, 
/**
 * Resume downloads that were running when the app last exited.
 */
resume_on_startup: boolean, 
/**
 * Pre-allocate the full file size when the size is known.
 */
preallocate: boolean, };
