// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Transfer mechanism used for a download.
 */
export type DownloadKind = "http" | "ftp" | "sftp" | "hls" | "dash" | "extractor";
