// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Category } from "./Category";
import type { ChecksumSpec } from "./ChecksumSpec";
import type { DownloadKind } from "./DownloadKind";
import type { DownloadStatus } from "./DownloadStatus";
import type { ErrorKind } from "./ErrorKind";
import type { MediaRequest } from "./MediaRequest";

/**
 * Persistent and live information about a download, as shown in the UI.
 */
export type DownloadInfo = { id: string, url: string, final_url: string | null, page_url: string | null, file_name: string, save_dir: string, kind: DownloadKind, status: DownloadStatus, category: Category, total_size: number | null, downloaded: number, 
/**
 * `None` until the server has been contacted.
 */
resumable: boolean | null, 
/**
 * Maximum connections configured for this download.
 */
max_connections: number, 
/**
 * Connections currently transferring data.
 */
active_connections: number, 
/**
 * Current speed in bytes/second.
 */
speed: number, 
/**
 * Average speed over the active transfer time, bytes/second.
 */
avg_speed: number, eta_secs: number | null, error: string | null, error_kind: ErrorKind | null, mime: string | null, referer: string | null, queue_id: string | null, priority: number, created_at: number, started_at: number | null, completed_at: number | null, scheduled_at: number | null, next_retry_at: number | null, retry_count: number, speed_limit: number, checksum: ChecksumSpec | null, 
/**
 * Result of the last checksum verification: `Some(true)` = matched.
 */
checksum_ok: boolean | null, media: MediaRequest | null, 
/**
 * Total active transfer time in milliseconds.
 */
elapsed_ms: number, 
/**
 * Whether authentication/cookie data is stored for this download.
 */
has_secrets: boolean, };
