// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DownloadInfo } from "./DownloadInfo";
import type { ProgressSnapshot } from "./ProgressSnapshot";

/**
 * Events published by the engine and forwarded to the UI.
 */
export type EngineEvent = { "type": "added", download: DownloadInfo, } | { "type": "updated", download: DownloadInfo, } | { "type": "removed", id: string, } | { "type": "progress", items: Array<ProgressSnapshot>, } | { "type": "completed", download: DownloadInfo, } | { "type": "failed", download: DownloadInfo, };
