// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Classification of a download failure, used by the UI to offer recovery.
 */
export type ErrorKind = "network" | "http" | "link_expired" | "remote_changed" | "resume_unsupported" | "auth" | "disk" | "disk_full" | "invalid_response" | "tool" | "unsupported" | "checksum_mismatch" | "other";
