// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtCaptureOrigin } from "./ExtCaptureOrigin";
import type { HeaderPair } from "./HeaderPair";

/**
 * A download handed over by the browser.
 */
export type ExtBrowserDownload = { url: string, referrer: string | null, page_url: string | null, file_name: string | null, mime: string | null, file_size: number | null, 
/**
 * `Cookie` header value for the URL, read with the browser's cookies API.
 */
cookies: string | null, user_agent: string | null, headers: Array<HeaderPair>, 
/**
 * Ask the user (show the add dialog) instead of starting silently.
 */
interactive: boolean, origin: ExtCaptureOrigin, };
