// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Capture configuration pushed to the extension.
 */
export type ExtBrowserConfig = { capture_downloads: boolean, capture_extensions: Array<string>, min_capture_size: number, excluded_sites: Array<string>, video_detection: boolean, floating_button: boolean, };
