// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MediaSourceKind } from "./MediaSourceKind";

export type ExtMediaContext = { url: string, kind: MediaSourceKind, page_url: string | null, referrer: string | null, cookies: string | null, user_agent: string | null, title: string | null, };
