// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtBrowserDownload } from "./ExtBrowserDownload";
import type { ExtMediaContext } from "./ExtMediaContext";
import type { MediaRequest } from "./MediaRequest";

export type ExtRequest = { id: number, } & ({ "type": "hello", extension_version: string, browser: string, protocol_version: number, } | { "type": "ping" } | { "type": "get_config" } | { "type": "add_download", download: ExtBrowserDownload, } | { "type": "add_batch", items: Array<ExtBrowserDownload>, page_url: string | null, } | { "type": "probe_media", media: ExtMediaContext, } | { "type": "download_media", media: ExtMediaContext, selection: MediaRequest, interactive: boolean, } | { "type": "show_app" });
