// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtBrowserConfig } from "./ExtBrowserConfig";
import type { MediaProbeResult } from "./MediaProbeResult";

export type ExtResponse = { 
/**
 * Request id; 0 for unsolicited notifications.
 */
id: number, } & ({ "type": "hello", app_version: string, protocol_version: number, compatible: boolean, 
/**
 * Shown to the user when `compatible` is false.
 */
message: string | null, config: ExtBrowserConfig, } | { "type": "pong" } | { "type": "config", config: ExtBrowserConfig, } | { "type": "added", accepted: boolean, 
/**
 * Present when the download was created immediately.
 */
download_id: string | null, 
/**
 * The user is being asked (add dialog shown).
 */
pending: boolean, reason: string | null, } | { "type": "batch_added", count: number, } | { "type": "media", result: MediaProbeResult, } | { "type": "ok" } | { "type": "error", code: string, message: string, });
