// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConflictPolicy } from "./ConflictPolicy";
import type { DuplicatePolicy } from "./DuplicatePolicy";

export type GeneralSettings = { 
/**
 * Default download directory (empty = OS "Downloads" folder).
 */
download_dir: string, 
/**
 * Save files into per-category sub folders (Video, Music, ...).
 */
category_folders: boolean, launch_at_startup: boolean, start_minimized: boolean, minimize_to_tray: boolean, close_to_tray: boolean, notify_on_complete: boolean, notify_on_error: boolean, 
/**
 * Watch the clipboard for downloadable links (opt-in).
 */
clipboard_monitor: boolean, conflict_policy: ConflictPolicy, duplicate_policy: DuplicatePolicy, 
/**
 * Show the "download file info" dialog for downloads sent by the browser.
 */
show_add_dialog_for_browser: boolean, 
/**
 * Open the progress window when a download starts.
 */
show_progress_window: boolean, 
/**
 * Show the completion dialog when a download finishes.
 */
show_complete_dialog: boolean, };
