// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A custom HTTP header.
 */
export type HeaderPair = { name: string, value: string, };
