// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MediaSourceKind } from "./MediaSourceKind";
import type { OutputContainer } from "./OutputContainer";

/**
 * A media download selection.
 */
export type MediaRequest = { kind: MediaSourceKind, 
/**
 * Manifest URL, direct URL or page URL depending on `kind`.
 */
url: string, 
/**
 * Selected video (or muxed) format id; `None` = best.
 */
format_id: string | null, 
/**
 * Separate audio format id (DASH / extractor), `None` = best.
 */
audio_format_id: string | null, 
/**
 * Subtitle languages to download.
 */
subtitle_languages: Array<string>, 
/**
 * Embed subtitles into the container instead of separate files.
 */
embed_subtitles: boolean, container: OutputContainer, title: string | null, 
/**
 * Preferred maximum height used when `format_id` is `None`.
 */
max_height: number | null, };
