// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OutputContainer } from "./OutputContainer";
import type { QualityPreference } from "./QualityPreference";

export type MediaSettings = { preferred_quality: QualityPreference, output_container: OutputContainer, download_subtitles: boolean, subtitle_languages: Array<string>, embed_subtitles: boolean, 
/**
 * Parallel segment downloads for HLS/DASH.
 */
segment_concurrency: number, };
