// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One selectable rendition of a media resource.
 */
export type MediaFormat = { 
/**
 * Opaque identifier (variant URL hash, DASH representation id, yt-dlp format id).
 */
id: string, 
/**
 * Human readable label, e.g. "1080p · 4.8 Mbps · H.264".
 */
label: string, has_video: boolean, has_audio: boolean, ext: string | null, width: number | null, height: number | null, fps: number | null, 
/**
 * Bits per second.
 */
bitrate: number | null, vcodec: string | null, acodec: string | null, 
/**
 * Exact or estimated size in bytes.
 */
filesize: number | null, language: string | null, 
/**
 * Direct URL of this rendition when known (not exposed for extractor formats).
 */
url: string | null, };
