// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MediaFormat } from "./MediaFormat";
import type { MediaSourceKind } from "./MediaSourceKind";
import type { SubtitleTrack } from "./SubtitleTrack";

/**
 * Result of probing a media URL or page.
 */
export type MediaProbeResult = { kind: MediaSourceKind, url: string, title: string | null, duration_secs: number | null, thumbnail: string | null, formats: Array<MediaFormat>, subtitles: Array<SubtitleTrack>, 
/**
 * Name of the yt-dlp extractor, for page probes.
 */
extractor: string | null, 
/**
 * The stream is live; it cannot be downloaded to completion.
 */
is_live: boolean, 
/**
 * DRM / encryption that the app refuses to handle was detected.
 */
drm_protected: boolean, };
