// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a media resource was discovered / is retrieved.
 */
export type MediaSourceKind = "direct" | "hls" | "dash" | "page";
