// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProxySettings } from "./ProxySettings";

export type NetworkSettings = { proxy: ProxySettings, connect_timeout_secs: number, 
/**
 * Abort a connection that receives no data for this long.
 */
read_timeout_secs: number, user_agent: string, max_redirects: number, };
