// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Container requested for the final media file.
 */
export type OutputContainer = "mp4" | "mkv" | "original" | "m4a" | "mp3";
