// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AddDownloadRequest } from "./AddDownloadRequest";

/**
 * A download handed over by the browser, waiting for the user's decision.
 */
export type PendingCapture = { id: string, request: AddDownloadRequest, duplicate_of: string | null, };
