// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PowerSettings = { 
/**
 * Pause the queue while running on battery below `battery_threshold`.
 */
pause_on_low_battery: boolean, battery_threshold: number, 
/**
 * Do not start queued downloads on metered connections (Windows only).
 */
pause_on_metered: boolean, };
