// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DownloadStatus } from "./DownloadStatus";
import type { SegmentProgress } from "./SegmentProgress";

/**
 * Periodic progress report for a running download.
 */
export type ProgressSnapshot = { id: string, status: DownloadStatus, downloaded: number, total_size: number | null, speed: number, avg_speed: number, eta_secs: number | null, active_connections: number, elapsed_ms: number, segments: Array<SegmentProgress>, 
/**
 * Free-form stage description for media jobs ("Downloading video 3/120").
 */
stage: string | null, };
