// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProxyMode } from "./ProxyMode";

export type ProxySettings = { mode: ProxyMode, host: string, port: number, username: string, 
/**
 * Indicates a password is stored in the secret store. The password
 * itself is never part of the settings document.
 */
has_password: boolean, 
/**
 * Hosts that bypass the proxy (comma separated patterns).
 */
bypass: string, };
