// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type QualityPreference = "best" | "p2160" | "p1440" | "p1080" | "p720" | "p480" | "p360" | "audio_only";
