// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PostAction } from "./PostAction";
import type { Schedule } from "./Schedule";

/**
 * A download queue.
 */
export type QueueInfo = { id: string, name: string, 
/**
 * Maximum downloads of this queue running at once (1 = sequential).
 */
max_concurrent: number, 
/**
 * Queue processing is running.
 */
running: boolean, schedule: Schedule, post_action: PostAction, 
/**
 * Retry failed items automatically when the queue processes them.
 */
retry_failed: boolean, sort_order: number, built_in: boolean, };
