// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PostAction } from "./PostAction";
import type { Schedule } from "./Schedule";

export type QueueUpdate = { name: string | null, max_concurrent: number | null, schedule: Schedule | null, post_action: PostAction | null, retry_failed: boolean | null, };
