// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PostAction } from "./PostAction";
import type { PowerHold } from "./PowerHold";
import type { QueueInfo } from "./QueueInfo";

/**
 * Notifications from the scheduler.
 */
export type SchedulerEvent = { "type": "queues_changed", queues: Array<QueueInfo>, } | { "type": "queue_finished", queue_id: string, name: string, post_action: PostAction, completed: number, failed: number, } | { "type": "power_hold", hold: PowerHold | null, };
