// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Time window during which a queue may start downloads.
 */
export type Schedule = { enabled: boolean, 
/**
 * Local start time "HH:MM".
 */
start_time: string | null, 
/**
 * Local stop time "HH:MM"; running downloads are paused at this time.
 */
stop_time: string | null, 
/**
 * Days of week the schedule is active (0 = Sunday ... 6 = Saturday).
 * Empty = every day.
 */
days: Array<number>, };
