// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * State of one byte-range segment as reported by the engine.
 */
export type SegmentProgress = { index: number, 
/**
 * First byte of the segment.
 */
start: number, 
/**
 * One past the last byte (`null` while the size is unknown).
 */
end: number | null, 
/**
 * Bytes of this segment written to disk.
 */
written: number, 
/**
 * A connection is currently assigned to the segment.
 */
active: boolean, 
/**
 * Current speed of the connection serving this segment, bytes/second.
 */
speed: number, done: boolean, };
