// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CategoryStat } from "./CategoryStat";
import type { DailyStat } from "./DailyStat";
import type { MonthlyStat } from "./MonthlyStat";

export type StatsSummary = { 
/**
 * Bytes transferred over the network, all time.
 */
total_bytes: number, total_completed: number, total_failed: number, today_bytes: number, month_bytes: number, 
/**
 * Last 30 days, oldest first.
 */
daily: Array<DailyStat>, 
/**
 * Last 12 months, oldest first.
 */
monthly: Array<MonthlyStat>, by_category: Array<CategoryStat>, 
/**
 * Highest average speed of a completed download, bytes/second.
 */
best_avg_speed: number, };
