// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SubtitleTrack = { language: string, name: string | null, ext: string | null, 
/**
 * Automatically generated captions.
 */
automatic: boolean, url: string | null, };
