// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Availability of a bundled tool.
 */
export type ToolStatus = { name: string, available: boolean, path: string | null, version: string | null, error: string | null, 
/**
 * Tool comes from the application bundle (as opposed to a dev fallback).
 */
bundled: boolean, };
