// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Category } from "./Category";
import type { DownloadKind } from "./DownloadKind";

/**
 * Information about a URL obtained by probing it before adding.
 */
export type UrlInfo = { url: string, final_url: string, file_name: string, total_size: number | null, resumable: boolean, mime: string | null, category: Category, kind: DownloadKind, 
/**
 * Directory the file would be saved to with current settings.
 */
suggested_dir: string, 
/**
 * Another download with the same URL already exists.
 */
duplicate_of: string | null, };
